teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 2
      z: 5
    scale_linear:
      x: 1.0
      y: 1.0
      z: 1.0
    scale_linear_turbo:
      x: 0.6
      y: 0.6
      z: 0.6

      
    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 1.0
    scale_angular_turbo:
      yaw: 2.5

    enable_button: 7
    # enable_turbo_button: 10